/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hsaturn.arduino.widgets.small;

import com.hsaturn.arduino.hardware.Module;
import com.hsaturn.arduino.message.Message;
import com.hsaturn.arduino.widgets.Widget;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;

/**
 *
 * @author hsaturn
 */
public class Stack extends Widget {

	/**
	 * Creates new form Stack
	 */
	public Stack(Module m) {
		super(m);
		initComponents();
		m.addObserver(this);
		setName("Stack");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("all")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lstStack = new javax.swing.JList<String>();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(Stack.class, "Stack.jLabel1.text")); // NOI18N

        lstStack.setBackground(new java.awt.Color(234, 234, 234));
        lstStack.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), org.openide.util.NbBundle.getMessage(Stack.class, "Stack.lstStack.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 10), new java.awt.Color(0, 0, 0))); // NOI18N
        lstStack.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(lstStack, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lstStack, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> lstStack;
    // End of variables declaration//GEN-END:variables

	@Override
	protected void onMessage(Message msg) {
		if (msg.get("stack") != null) {
			String stack = msg.get("stack").toString();
			DefaultListModel<String> model= new DefaultListModel<>();
			String[] elts = stack.split(" ");
			int iSize = Integer.parseInt(msg.get("stksize").toString());	// FIXME A quoi sert le converter int !!!! on y passe, mais on reconvertit en String pour refaire un int ...... ouch
			for(String str : elts)
			{
				if (iSize==0)
					break;
				iSize--;
				model.addElement(str);
			}
			lstStack.setModel(model);
		}
	}
}
